### ISSUE TITLE
icloud for linux stopped working on raspberry pi

### ISSUE THREAD

**Issue by dirkgently73** [cross-platform/icloud-for-linux#23]
Dear Marcus,

thank you very much for your app. It works fine on ubuntu and solus and it worked on raspberry pi (raspbian buster) after installing in devmode.
Then, at some point, it stopped working.

I tried 
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux****

and snap install icloud-for-linux --devmode

I also tried 

# Uninstall icloud-for-linux
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux

# Clear font cache
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
sudo fc-cache -f -v

# Re-install icloud-for-linux
snap install icloud-for-linux

I also reinstalled raspbian but still no luck.

but, when I try to launch it, I get

_pi@raspberrypi:~ $ icloud-for-linux.mail
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Sandboxing disabled by user.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted
pi@raspberrypi:~ $ [5189:5189:0100/000000.265286:ERROR:zygote_linux.cc(636)] Zygote could not fork: process_type renderer numfds 3 child_pid -1
[5189:5189:0100/000000.267693:ERROR:zygote_linux.cc(668)] write: Broken pipe

Thank you for your help.

regatds,

Paolo

**Comment by MarcusTomlinson** [comment]
Sounds like a graphics driver issue. Please try:

`QT_XCB_FORCE_SOFTWARE_OPENGL=1 icloud-for-linux.numbers`

If this works you may need to find a different graphics driver, or perhaps just an updated one.

Note: software rendering won’t work on Notes and Reminders as they require webgl.

**Comment by dirkgently73** [comment]
$ QT_XCB_FORCE_SOFTWARE_OPENGL=1 icloud-for-linux.numbers
2020/08/26 18:22:00.733766 system_key.go:127: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 1
Sandboxing disabled by user.
[24394:24558:0826/182222.313455:ERROR:ssl_client_socket_impl.cc(1101)] handshake failed; returned -1, SSL error code 1, net_error -107
js: Uncaught ReferenceError: jstProcess is not defined


still not working...
the system is uo to date.. which driver should I try?

Anyway, many thanks for your help.

**Comment by fechbmaster** [comment]
Got the same problem - any updates on this?

**Comment by MarcusTomlinson** [comment]
Sorry guys, not got around to setting up my rpi for this just yet. Will try over the weekend.

**Comment by MuellersPeter** [comment]
Same issue here. Any further information to fix this? It is a big need for me to use my iCloud on a Raspberry Pi.

**Comment by MarcusTomlinson** [comment]
Sorry this is taking so long guys. I _may_ have finally found the cause:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882805

Updating qtwebengine _might_ be all we need, I’m really not sure. Will dig a little more tomorrow.

**Comment by MarcusTomlinson** [comment]
This is now fixed in version 0.11.

**Comment by mcallaway** [comment]
I am still seeing this error on Raspberri Pi 2B:

    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    libEGL warning: DRI2: failed to authenticate
    ^C


    icloud-for-linux  0.11      213  candidate  marcustomlinson  -

**Comment by MarcusTomlinson** [comment]
@mcallaway, could you try reinstalling the stable version like so:
```
snap remove --purge icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

**Comment by mcallaway** [comment]
pi@raspberrypi:~ $ sudo snap remove --purge icloud-for-linux
    error: unknown flag `purge'
    pi@raspberrypi:~ $ sudo snap remove icloud-for-linux
    icloud-for-linux removed

    pi@raspberrypi:~ $ sudo snap install icloud-for-linux
    icloud-for-linux 0.11 from Marcus Tomlinson (marcustomlinson) installed
    pi@raspberrypi:~ $ sudo snap list
    Name              Version   Rev  Tracking  Publisher        Notes
    core20            20201210  906  stable    canonical✓       base
    icloud-for-linux  0.11      206  stable    marcustomlinson  -

    pi@raspberrypi:~ $ icloud-for-linux.notes 
    ... lots of output like this ...
    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    libEGL warning: DRI2: failed to authenticate
    ^C
    pi@raspberrypi:~ $ echo $?
    130

**Comment by MarcusTomlinson** [comment]
Hmm `error: unknown flag 'purge'`, looks like you're behind in updates. What distro and version are you running?

**Comment by MarcusTomlinson** [comment]
@mcallaway, ah apologies, I see the same errors on my raspberry pi too. You can actually ignore them. Just leave it to load a bit more and eventually the app will appear.

**Comment by mcallaway** [comment]
This is what I see now:

    pi@raspberrypi:~ $ cat /etc/issue
    Raspbian GNU/Linux 10 \n \l
    
    sudo apt update
    sudo apt full-upgrade
    
    ... a few packages are updated, but /etc/issue still shows 10
    
    pi@raspberrypi:~ $ cat /etc/issue
    Raspbian GNU/Linux 10 \n \l
    
    pi@raspberrypi:~ $ sudo snap list
    Name              Version   Rev  Tracking  Publisher        Notes
    core20            20201210  906  stable    canonical✓       base
    icloud-for-linux  0.11      213  stable    marcustomlinson  -
    
    pi@raspberrypi:~ $ /snap/bin/icloud-for-linux.notes
    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    ... lots of output like that ...
    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
    libEGL warning: DRI2: failed to authenticate
    Sandboxing disabled by user.
    Trace/breakpoint trap
    pi@raspberrypi:~ $ echo $?
    133
